### ISSUE TITLE
NPC icon for Titan

### ISSUE THREAD

**Issue by tetron** [bdjeffyp/ffr-tracker#7]
Since Titan's cave can be an FFR key item location it would be helpful to have him on the tracker -- and it'll fill in that last gap in the NPCs section.

**Comment by bdjeffyp** [comment]
Thanks for bringing this up. Sorry for the delay in seeing this. I thought I would get notifications when people create issues after the changes I made to my settings, but it still doesn't seem to work. 😅
Anyway, I'll take a look at doing this soon. It is a good point to include the Titan for the same reason as Dr. Unne. However, it goes against the aesthetic I had initially set up with the NPC box. I will probably rearrange the NPCs into vanilla order rather than the three sections I had before (story on top, fetch on bottom, and fairy quest on the right side).

**Comment by bdjeffyp** [comment]
Titan has now been added! As a result of this, I rearranged the NPCs in the order in which you visit them in the vanilla game, as I discussed above. Note that the robot/shopkeeper/fairy and Dr. Unne/Lefenian quests are placed in an order that I normally completed them in and may be done in any order in the vanilla game so that was just a personal preference there. Anyway, I hope this change helps. It verified that it is live now.

Let me know if you have any other suggestions!
